# Generated by Django 4.2.1 on 2023-05-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='rooom_name',
            new_name='room_name',
        ),
    ]
